import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:sgrv_frontend/core/config/api_config.dart';
import 'package:sgrv_frontend/core/storage/token_storage.dart';
import '../models/foto_vehiculo.dart';
import '../providers/vehiculo_media_provider.dart';

class VehiculoGaleriaSection extends StatelessWidget {
  const VehiculoGaleriaSection({required this.idVehiculo,super.key});final int idVehiculo;
  @override Widget build(BuildContext context){final p=context.watch<VehiculoMediaProvider>();if(p.loading)return const Center(child:CircularProgressIndicator());return ListView(children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Galería del vehículo',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Text('Portada, exterior e interior en un solo lugar.')])),FilledButton.icon(onPressed:()=>_pick(context),icon:const Icon(Icons.add_a_photo_rounded),label:const Text('Agregar foto'))]),const SizedBox(height:16),if(p.fotos.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(44),child:Center(child:Column(children:[Icon(Icons.photo_library_outlined,size:48),SizedBox(height:10),Text('Todavía no hay fotos',style:TextStyle(fontWeight:FontWeight.w700))]))))else LayoutBuilder(builder:(context,c)=>GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:c.maxWidth>1000?3:c.maxWidth>600?2:1,crossAxisSpacing:14,mainAxisSpacing:14,childAspectRatio:1.45),itemCount:p.fotos.length,itemBuilder:(_,i)=>_PhotoCard(photo:p.fotos[i],idVehiculo:idVehiculo))) ]);}
  Future<void> _pick(BuildContext context)async{final file=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:88,maxWidth:2200);if(file==null||!context.mounted)return;final bytes=await file.readAsBytes();if(!context.mounted)return;final ext=file.name.toLowerCase();final type=ext.endsWith('.png')?'image/png':ext.endsWith('.webp')?'image/webp':'image/jpeg';final ok=await context.read<VehiculoMediaProvider>().subir(idVehiculo,bytes,file.name,type);if(!ok&&context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(context.read<VehiculoMediaProvider>().error??'No fue posible cargar la foto.')));}
}

class _PhotoCard extends StatelessWidget{const _PhotoCard({required this.photo,required this.idVehiculo});final FotoVehiculo photo;final int idVehiculo;
  @override Widget build(BuildContext context)=>Card(clipBehavior:Clip.antiAlias,child:Stack(fit:StackFit.expand,children:[FutureBuilder<String?>(future:TokenStorage.getToken(),builder:(_,s)=>Image.network('${ApiConfig.baseUrl}${photo.url}',fit:BoxFit.cover,headers:s.data==null?null:{'Authorization':'Bearer ${s.data}'},errorBuilder:(_,_,_)=>const ColoredBox(color:Color(0xFFEFF2F8),child:Icon(Icons.broken_image_outlined,size:44)))),Positioned(left:10,top:10,child:photo.esPrincipal?const Chip(avatar:Icon(Icons.star_rounded,size:17),label:Text('Portada')):const SizedBox.shrink()),Positioned(right:6,top:6,child:PopupMenuButton<String>(onSelected:(v){final p=context.read<VehiculoMediaProvider>();if(v=='principal')p.hacerPrincipal(idVehiculo,photo.idFoto);if(v=='delete')p.eliminar(idVehiculo,photo.idFoto);},itemBuilder:(_)=>[if(!photo.esPrincipal)const PopupMenuItem(value:'principal',child:Text('Usar como portada')),const PopupMenuItem(value:'delete',child:Text('Eliminar'))])),Positioned(left:0,right:0,bottom:0,child:Container(padding:const EdgeInsets.all(12),decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black87])),child:Text(photo.titulo??photo.textoAlternativo??'Foto del vehículo',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700))))]));}
